pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/dvish2003/phamcy_backend.git'
            }
        }
        stage('Build') {
            steps {
                echo 'Building project...'
            }
        }
        stage('Test') {
            steps {
                echo 'Running tests...'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying application...'
            }
        }
    }
}

